name: e2e
on:
  pull_request:
  push:
    branches:
      - 'release-*'
      - 'master'
      - 'main'
    tags:
      - 'v*'
jobs:
  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite: [alertmanager, prometheus, thanosruler]
        include:
          - suite: alertmanager
            prometheus: "exclude"
            alertmanager: ""
            thanosruler: "exclude"
            featureGated: "include"
          - suite: prometheus
            prometheus: ""
            alertmanager: "exclude"
            thanosruler: "exclude"
            featureGated: "include"
          - suite: thanosruler
            prometheus: "exclude"
            alertmanager: "exclude"
            thanosruler: ""
            featureGated: "include"
    steps:
    - uses: actions/checkout@v2
    - name: Import environment variables from file
      run: cat ".github/env" >> $GITHUB_ENV
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '${{ env.golang-version }}'
    - name: Build images
      run: |
        export SHELL=/bin/bash
        make build image
    - name: Start KinD
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: ${{ env.kind-version }}
        image: ${{ env.kind-image }}
        wait: 300s
        config: /test/e2e/kind-conf.yaml
    - name: Wait for cluster to finish bootstraping
      run: |
        kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s
        kubectl cluster-info
        kubectl get pods -A
    - name: Load images
      run: |
        kind load docker-image quay.io/prometheus-operator/prometheus-operator:$(git rev-parse --short HEAD)
        kind load docker-image quay.io/prometheus-operator/prometheus-config-reloader:$(git rev-parse --short HEAD)
        kubectl apply -f scripts/kind-rbac.yaml
    - name: Run tests
      run: >
        EXCLUDE_ALERTMANAGER_TESTS=${{ matrix.alertmanager }}
        EXCLUDE_PROMETHEUS_TESTS=${{ matrix.prometheus }}
        EXCLUDE_THANOSRULER_TESTS=${{ matrix.thanosruler }}
        FEATURE_GATED_TESTS=${{ matrix.featureGated }}
        make test-e2e
